replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

config:
  POSTGRES_DB: "ordermanagementdb"
  POSTGRES_URL: ""
  MERCADO_PAGO_EXTERNAL_POS_ID: "EXTERNALIDPOSTESTE"
  MERCADO_PAGO_URL: "https://api.mercadopago.com"
  SERVER_PORT: "8080"

secrets:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  MERCADO_PAGO_ACCESS_TOKEN: ""
