apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  MERCADO_PAGO_ACCESS_TOKEN: {{ .Values.secrets.MERCADO_PAGO_ACCESS_TOKEN | b64enc | quote }}
