apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: ordermanagementdb
  POSTGRES_URL: jdbc:postgresql://tech-challenge-postgres.cwephenukgyv.us-east-1.rds.amazonaws.com:5432/ordermanagementdb
  MERCADO_PAGO_EXTERNAL_POS_ID: EXTERNALIDPOSTESTE
  MERCADO_PAGO_URL: https://api.mercadopago.com
  SERVER_PORT: "8080"
