apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  MERCADO_PAGO_ACCESS_TOKEN: QVBQX1VTVC01ODI2NzU4NjIxMjYzNDMzLTA3MjYxNS0yODZlYWIwOGQyZDIyZTQyYzVlZTc4ZTVmMjkxZTc5My0yNTgwODk0MDI5
