apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_USER: b3JkZXJtYW5hZ2VtZW50
  POSTGRES_PASSWORD: cGFzc2RiMTIzNDU
  MERCADO_PAGO_ACCESS_TOKEN: QVBQX1VTVC01ODI2NzU4NjIxMjYzNDMzLTA3MjYxNS0yODZlYWIwOGQyZDIyZTQyYzVlZTc4ZTVmMjkxZTc5My0yNTgwODk0MDI5
