apiVersion: v1
kind: Service
metadata:
  name: order-management-backend
spec:
  selector:
    app: order-management
    component: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer