apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: backend
    spec:
      containers:
        - name: order-management
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secrets.externalSecret }}{{ .Values.secrets.externalSecret }}{{ else }}{{ .Release.Name }}-secret{{ end }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secrets.externalSecret }}{{ .Values.secrets.externalSecret }}{{ else }}{{ .Release.Name }}-secret{{ end }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: SERVER_PORT
            - name: MERCADO_PAGO_EXTERNAL_POS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MERCADO_PAGO_EXTERNAL_POS_ID
            - name: MERCADO_PAGO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MERCADO_PAGO_URL
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secrets.externalSecret }}{{ .Values.secrets.externalSecret }}{{ else }}{{ .Release.Name }}-secret{{ end }}
                  key: MERCADO_PAGO_ACCESS_TOKEN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
