name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      eks_cluster_name:
        description: 'EKS Cluster Name'
        required: false
        default: 'eks-cluster-tech-challenge-ordermanagement'
      ecr_repo_name:
        description: 'ECR Repository Name'
        required: false
        default: 'tech-challenge-ordermanagement-repo'

env:
  AWS_REGION: us-east-1

jobs:
  gradlew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage
        run: ./gradlew clean build

  deploy:
    needs: gradlew
    runs-on: ubuntu-latest
    environment: production
    env:
      EKS_CLUSTER_NAME: ${{ github.event.inputs.eks_cluster_name }}
      ECR_REPO_NAME: ${{ github.event.inputs.ecr_repo_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}

      - name: Setup kubectl for EKS
        uses: kodermax/kubectl-aws-eks@v1
        with:
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          region: ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
