name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      eks_cluster_name:
        description: 'EKS Cluster Name'
        required: false
        default: 'eks-cluster-tech-challenge-ordermanagement'
      ecr_repo_name:
        description: 'ECR Repository Name'
        required: false
        default: 'tech-challenge-ordermanagement-repo'

env:
  AWS_REGION: us-east-1

jobs:
  gradlew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage
        run: ./gradlew clean build

  deploy:
    needs: gradlew
    runs-on: ubuntu-latest
    environment: production
    env:
      EKS_CLUSTER_NAME: ${{ github.event.inputs.eks_cluster_name }}
      ECR_REPO_NAME: ${{ github.event.inputs.ecr_repo_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:latest

      - name: Setup kubectl
        uses: aws-actions/setup-kubectl@v2

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Substitui o placeholder ${registry} no deployment.yaml pelo ECR registry real
          sed -i "s|\${registry}|$ECR_REGISTRY|g" .github/k8s/deployment.yaml
          
          # Atualiza kubeconfig para o cluster dinâmico
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          
          # Aplica deployment e service
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
